### PR TITLE
Fixed reference & typos in docs

### PR DESCRIPTION
**Pull request by edjiang**

### CODE REVIEW

**Comment by edjiang** [comment]
Hey @bretterer, what can I do to get this merged?

**Comment by bretterer** [comment]
@edjiang I have these changes merged into my local development and will be released when I push some code updates as well.

**Comment by edjiang** [comment]
Awesome!

**Comment by bretterer** [comment]
Changed merged into dev branch.  Not sure what happened here and why it didnt "merge" this PR.  Closing since the changes are there.

**Pull request closed without merging**
